### ISSUE TITLE
lix-website repo is not sync on git.lix.systems

### ISSUE THREAD

**Issue by sinavir** [lix-project/lix-website#3]
main is pointing to 0d006b3f801bdf67c015ace716bffde0719d79ca on git.lix.systems

https://git.lix.systems/lix-project/lix-website

**Comment by IreneKnapp** [comment]
hi! oh. okay Jade and I are trying to figure it out

**Comment by IreneKnapp** [comment]
this had never been set up. it is set up now, so the problem shouldn't recur. thanks for pointing it out!
